### ISSUE TITLE
Textbook Solutions Error! Can't get an answer

### ISSUE THREAD

**Issue by pikagone** [jhnqch/chegg#1]
When I use this link (Textbook) the bot gives an error!

https://www.chegg.com/homework-help/wacc-optimal-capital-budget-adams-corporation-considering-fo-chapter-10-problem-18p-solution-9781337395250-exc

Thanks bro!

**Comment by jhnqch** [comment]
Hi! This is an old project I recently uploaded, but I do not work on this project anymore. Also, yes it does not work on textbook solutions, only for solutions answered by experts.

**Comment by pikagone** [comment]
Thanks! Would you mind adding a solution to make it work on textbooks, or do you have a new project on Chegg bots?
@jhnqch
